name: Build Geode Android64

on:
  workflow_dispatch:
  push:
    branches: ["**"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Android64 Geode mod
        uses: geode-sdk/build-geode-mod@main
        with:
          target: Android64

      - name: Upload .geode
        uses: actions/upload-artifact@v4
        with:
          name: TrajectoryBot-Android64
          path: output/*.geode
          
